name: Build tools

on:
  workflow_run:
    workflows: ["Makefile CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Build tool: fat"
      run: make tools_fat

    - name: "Test tool: fat"
      run: ./build/tools/fat build/main_floppy.img "TEST    TXT"
