name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install mtools
      run: sudo apt-get install -y mtools
    
    - name: Install qemu
      run: sudo apt-get install -y qemu-system
    
    - name: Setup nasm
      uses: ilammy/setup-nasm@v1.2.1
      with:
        version: 2.14.02
    
    - name: Setup Open-Watcom-V2
      uses: open-watcom/setup-watcom@v0
      with:
        version: "2.0"
    
    - name: Try to build
      run: make
  
    - name: "Build tool: fat"
      run: |
        make tools_fat
        ./build/tools/fat build/main_floppy.img "TEST    TXT"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/main_floppy.img
        prerelease: true
        body: Test release by Github Actions
        draft: true
