name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install mtools
      run: sudo apt-get install -y mtools
    
    - name: Install nasm
      uses: ilammy/setup-nasm@v1.2.1
      with:
        version: 2.14.02
    
    - name: Try to build
      run: make
